import 'package:barrani/engine/rng.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  // Reference values generated by the TypeScript implementation. If these ever
  // diverge, the two apps would deal different rounds from the same seed.
  test('matches the TypeScript mulberry32 bit for bit', () {
    final rng = Rng(42);
    final actual = List.generate(8, (_) => rng.next());
    expect(actual, [
      0.6011037519201636,
      0.44829055899754167,
      0.8524657934904099,
      0.6697340414393693,
      0.17481389874592423,
      0.5265925421845168,
      0.2732279943302274,
      0.6247446539346129,
    ]);
  });

  test('matches TypeScript for a second seed', () {
    final rng = Rng(1234);
    expect(List.generate(4, (_) => rng.next()), [
      0.07329497812315822,
      0.7034119898453355,
      0.9028560190927237,
      0.9705493662040681,
    ]);
  });

  test('shuffle matches the TypeScript ordering', () {
    expect(Rng(9).shuffle([0, 1, 2, 3, 4, 5, 6, 7]), [7, 6, 3, 2, 4, 0, 5, 1]);
  });

  test('the same seed produces the same sequence', () {
    final a = Rng(42);
    final b = Rng(42);
    expect(List.generate(20, (_) => a.next()), List.generate(20, (_) => b.next()));
  });

  test('different seeds produce different sequences', () {
    final a = Rng(1);
    final b = Rng(2);
    expect(
      List.generate(20, (_) => a.next()),
      isNot(List.generate(20, (_) => b.next())),
    );
  });

  test('values stay in [0, 1)', () {
    final rng = Rng(7);
    for (var i = 0; i < 5000; i++) {
      final v = rng.next();
      expect(v, greaterThanOrEqualTo(0));
      expect(v, lessThan(1));
    }
  });

  test('shuffle returns a permutation and does not mutate the input', () {
    final input = [1, 2, 3, 4, 5, 6, 7, 8];
    final frozen = List.of(input);
    final out = Rng(3).shuffle(input);
    expect(out.length, input.length);
    expect(out.toList()..sort(), frozen);
    expect(input, frozen);
  });

  test('pickIndex stays in range and eventually reaches every index', () {
    final rng = Rng(11);
    final seen = <int>{};
    for (var i = 0; i < 2000; i++) {
      final index = rng.pickIndex(5);
      expect(index, inInclusiveRange(0, 4));
      seen.add(index);
    }
    expect(seen.length, 5);
  });
}
