/** Every user-facing string. Arabic-script Tunisian Derja only — never inline in a component. */
export const strings = {
  appName: "برّاني",
  tagline: "لعبة الجماعة، تلفون واحد",

  // Reveal
  holdToReveal: "شدّ باهي باش تشوف الكلمة",
  holdingHint: "ما تفلتش...",

  // Setup
  start: "ابدا",
  players: "اللاعبين",
  packs: "الحزم",
  options: "الخيارات",
  rules: "قواعد اللعبة",
  back: "أرجع",
  playerNamePlaceholder: "اسم اللاعب",
  addPlayer: "زيد",
  removePlayer: "نحّي",
  needMorePlayers: "لازم 3 لاعبين على الأقل باش تبدا",
  tableFull: "وصلت 12 لاعب، ما تنجمش تزيد",
  tierFamily: "عايلي",
  tierFriends: "بين الأصحاب",
  unlockFriends: "افتح حزم الأصحاب",
  friendsWarning: "فيها سلاڨ و عبارات بين الأصحاب. افتحها كان الجماعة الكل موافقة.",
  needOnePack: "اختار حزمة واحدة على الأقل",
  variant: "نوع الدورة",
  variantBarrani: "البرّاني",
  variantChbih: "الشبيه",
  variantRandom: "عشوائي",
  variantBarraniHint: "البرّاني يعرف روحو، أما ما عندوش كلمة",
  variantChbihHint: "البرّاني عندو كلمة قريبة، و ما يعرفش إنو هو البرّاني",
  impostorCount: "عدد البرانية",
  discussionTime: "وقت النقاش",
  noTimer: "بلا وقت",
  minutes: "دقايق",

  // Round
  handoffTo: "الفون لـ",
  iAm: "أنا",
  next: "عدّي",
  youAreBarrani: "إنت البرّاني",
  barraniHint: "ما عندكش كلمة. اسمع مليح و مثّل روحك.",
  yourWord: "كلمتك",
  turnOf: "الدور متاع",
  asks: "يسأل",
  questionHint: "اسألو سؤال محيّر على الكلمة. لازم جوابو يفضحو كان ما يعرفهاش.",
  asked: "سأل و جاوب",
  discussionTitle: "تحاوروا",
  startVote: "نصوّتوا",
  voteTitle: "شكون البرّاني؟",
  caught: "طلع برّاني!",
  missed: "لا، هذا ما كانش برّاني",
  stealBackPrompt: "البرّاني ينجم يربح الدورة كان عرف الكلمة",
  guessedRight: "عرفها",
  guessedWrong: "ما عرفهاش",
  secretWordWas: "الكلمة كانت",
  groupWordWas: "كلمة الجماعة كانت",
  barraniWas: "البرّاني كان",
  scores: "النقاط",
  nextRound: "دورة أخرى",
  endGame: "سالمة",
  exhausted: "كل الكلمات تعدّاو. نعاودوا من الأول؟",
  recycle: "عاود من الأول",

  // Rules
  version: "النسخة",
  rulesBody: [
    "تلفون واحد يدور على الجماعة. كل واحد يشدّ باهي باش يشوف كلمتو، ثم يعدّي التلفون.",
    "واحد فيكم هو البرّاني. في نوع «البرّاني» ما عندوش كلمة و يعرف روحو. في نوع «الشبيه» عندو كلمة قريبة و ما يعرفش.",
    "بعد ما الكل يشوف كلمتو، التطبيق يختار لكل واحد شكون يسألو. اسألو سؤال محيّر على الكلمة، و هو يجاوب قدّام الجماعة.",
    "بعدها تحاوروا و صوّتوا على شكون البرّاني.",
    "كان لقيتوه، ينجم يربح الدورة كان عرف كلمة الجماعة. كان غلطتو، البرّاني يربح.",
  ],
} as const;
